title: "My Jekyll Website"
description: "A simple website powered by Jekyll and GitHub Pages"
theme: jekyll-theme-cayman # or another GitHub Pages-supported theme
baseurl: "/Okay" # the name of your GitHub repository
url: "https://ProsperityHo.github.io" # your GitHub Pages URL
